spring:
  config:
    activate:
      on-profile: test
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  async:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 100

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/concert_test
    username: root
    password: root

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
      auto-offset-reset: earliest

slack:
  webhook:
    url: https://hooks.slack.com/services/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
