### 토큰 발급
GET http://localhost:8080/waiting/check

### 콘서트 조회
GET http://localhost:8080/concerts?page=0&size=5
Authorization: fffbfc0e-edaa-42a1-b4ef-27b09fa91f40

### 콘서트 일정 조회
GET http://localhost:8080/concerts/4/schedules?
    startDate=2024-05-30&
    endDate=2024-12-30
Authorization: fffbfc0e-edaa-42a1-b4ef-27b09fa91f40

