version: '3.8'
services:
  local-db:
    image: library/mysql:8.0.23
    container_name: mysql
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --sql-mode=NO_AUTO_VALUE_ON_ZERO,STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    volumes:
      - type: bind
        source: C:/DEV/docker/mysql8 # OS에 따라 경로 설정 변경
        target: /var/lib/mysql
