# 1 워크플로의 이름 지정
name: 'concert_reservation_service'

# 2 워크플로가 시작될 조건 지정
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest # 3 실행 환경 지정

    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: concert_test
          MYSQL_USER: test
          MYSQL_PASSWORD: 1234

    #4 실행스텝지정
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash
      - name: Build with Gradle
        run: ./gradlew build -x test
        shell: bash
#      - name: Test with Gradle
#        run: SPRING_PROFILES_ACTIVE=[local] ./gradlew clean test
#        shell: bash
